"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { jobs, readIds, savedKey } from "@/lib/jobs";
import { MagnifyingGlassIcon, MapPinIcon, BriefcaseIcon, HeartIcon, SparklesIcon } from "@heroicons/react/24/outline";

export default function JobsPage() {
  const [query, setQuery] = useState(""); const [location, setLocation] = useState("Tất cả địa điểm"); const [category, setCategory] = useState("Tất cả ngành nghề"); const [sort, setSort] = useState("Phù hợp nhất"); const [saved, setSaved] = useState<number[]>([]); const [onlySaved, setOnlySaved] = useState(false);
  useEffect(() => { setSaved(readIds(savedKey)); }, []);
  const filtered = useMemo(() => { let list = jobs.filter((job) => `${job.title} ${job.company} ${job.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase()) && (location === "Tất cả địa điểm" || job.location === location) && (category === "Tất cả ngành nghề" || job.category === category) && (!onlySaved || saved.includes(job.id))); if (sort === "Mới đăng") list = [...list].sort((a, b) => a.age - b.age); if (sort === "Lương cao nhất") list = [...list].sort((a, b) => b.salary - a.salary); if (sort === "Phù hợp nhất") list = [...list].sort((a, b) => b.match - a.match); return list; }, [query, location, category, sort, onlySaved, saved]);
  function toggleSave(id: number) { const next = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id]; setSaved(next); localStorage.setItem(savedKey, JSON.stringify(next)); }
  return <main className="min-h-[65vh] px-5 py-12 lg:px-8"><div className="container mx-auto"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">VIEJOB · Cơ hội dành cho bạn</p><h1 className="mt-2 text-3xl font-black text-blue-gray-900">Tìm việc làm</h1><p className="mt-2 text-gray-500">Tìm kiếm và khám phá cơ hội từ các nhà tuyển dụng uy tín.</p>
    <div className="mt-7 grid gap-3 rounded-2xl border border-blue-gray-50 bg-white p-3 shadow-md md:grid-cols-[1.5fr_1fr_1fr]"><label className="flex items-center gap-3 rounded-xl bg-gray-50 px-4 py-3"><MagnifyingGlassIcon className="h-5 w-5 text-blue-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Chức danh, kỹ năng hoặc công ty" className="w-full bg-transparent text-sm outline-none" /></label><label className="flex items-center gap-2 rounded-xl bg-gray-50 px-4 py-3"><MapPinIcon className="h-5 w-5 text-blue-500" /><select value={location} onChange={(e) => setLocation(e.target.value)} className="w-full bg-transparent text-sm outline-none"><option>Tất cả địa điểm</option>{Array.from(new Set(jobs.map((job) => job.location))).map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex items-center gap-2 rounded-xl bg-gray-50 px-4 py-3"><BriefcaseIcon className="h-5 w-5 text-blue-500" /><select value={category} onChange={(e) => setCategory(e.target.value)} className="w-full bg-transparent text-sm outline-none"><option>Tất cả ngành nghề</option>{Array.from(new Set(jobs.map((job) => job.category))).map((item) => <option key={item}>{item}</option>)}</select></label></div>
    <div className="my-6 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-gray-600">Tìm thấy <b>{filtered.length}</b> việc làm</p><div className="flex items-center gap-3"><button onClick={() => setOnlySaved(!onlySaved)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${onlySaved ? "border-blue-600 bg-blue-50 text-blue-700" : "border-blue-gray-100 bg-white text-gray-600"}`}>{onlySaved ? "Đang xem việc đã lưu" : `Việc đã lưu (${saved.length})`}</button><label className="text-sm text-gray-600">Sắp xếp theo <select value={sort} onChange={(e) => setSort(e.target.value)} className="ml-2 rounded-lg border border-blue-gray-100 bg-white px-3 py-2"><option>Phù hợp nhất</option><option>Mới đăng</option><option>Lương cao nhất</option></select></label></div></div>
    <div className="grid gap-4 md:grid-cols-2">{filtered.map((job) => <article key={job.id} className="rounded-2xl border border-blue-gray-50 bg-white p-5 transition hover:shadow-lg"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-blue-50 text-xl font-bold text-blue-600">{job.logo}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><Link href={`/jobs/${job.id}`} className="font-bold text-blue-gray-900 hover:text-blue-600">{job.title}</Link><p className="mt-1 text-sm text-gray-500">{job.company}</p></div><button aria-label="Lưu việc làm" onClick={() => toggleSave(job.id)} className="rounded-full p-2 text-gray-400 hover:bg-red-50 hover:text-red-500"><HeartIcon className={`h-5 w-5 ${saved.includes(job.id) ? "fill-red-500 text-red-500" : ""}`} /></button></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-gray-500"><span>{job.location}</span><span>{job.type}</span><b className="text-green-700">{job.salary} triệu/tháng</b><span>{job.posted}</span></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-blue-gray-50 pt-3"><div className="flex flex-wrap gap-2">{job.skills.map((skill) => <span key={skill} className="rounded bg-gray-50 px-2 py-1 text-xs text-gray-600">{skill}</span>)}</div><span className="flex items-center gap-1 text-xs font-bold text-blue-600"><SparklesIcon className="h-4 w-4" />{job.match}% phù hợp</span></div></div></div></article>)}</div>{!filtered.length && <p className="py-16 text-center text-gray-500">Không tìm thấy việc làm phù hợp với bộ lọc.</p>}</div></main>;
}
